name: Flutter iOS

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - uses: subosito/flutter-action@v1.3.2
      with:
        flutter-version: '1.17.x'
        channel: 'beta'
    - name: download libzap
      run: wget https://github.com/djpnewton/libzap/releases/download/v12/ios.zip
    - name: extract libzap
      run: mkdir -p native-libraries/ios; cd native-libraries/ios; unzip ../../ios.zip
    - run: flutter pub get
    #- run: flutter test
    - run: flutter build ios --release --no-codesign
    - name: upload build
      uses: actions/upload-artifact@v1
      with:
        name: Runner.app
        path: build/ios/iphoneos/Runner.app
